FROM mysql:5.6

# TO DO создание и привелегии базы с suggest, и загрузка дампов при первой установке
#COPY ./conf /etc/mysql/conf.d

RUN echo "Europe/Moscow" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata